#!/usr/bin/env sh
# Give a battery name (e.g. BAT0) as an argument.

battery_name="BAT0"

case $BLOCK_BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


capacity=$(cat /sys/class/power_supply/"$battery_name"/capacity) || exit

status=$(
    cat /sys/class/power_supply/"$battery_name"/status |
	sed 's/Discharging/battery/'
) || exit


echo "$capacity% $status"
