#!/usr/bin/bash

# disable/enable displays when reloading sway in "clamshell mode"
# https://github.com/swaywm/sway/wiki#clamshell-mode
LAPTOP="LVDS-1"

if grep -q open /proc/acpi/button/lid/LID/state; then
    swaymsg output $LAPTOP enable
else
    swaymsg output $LAPTOP disable
fi
