#!/bin/zsh

PYTHON="python"
IDE="magic-tiler-ide"


cd $HOME/workspace/abstractlyZach/magic-tiler

selection=$(poetry run magic-tiler list-layouts | floating-fzf)
poetry run magic-tiler -vv open "${selection}" 2> $HOME/magic-tiler.log 1> $HOME/magic-tiler.log
