#!/usr/bin/env sh
# fuzzy-find all emoji characters and then copy it to the clipboard
# Shows the selected character in dunst if running.

emoji_list="$HOME/.config/emoji"

# exit if we don't have a clipboard installed
which "$CLIPBOARD" >/dev/null || exit

chosen_entry=$(grep -v "#" "$emoji_list" | floating-fzf)
[ "$chosen_entry" != "" ] || exit

chosen_emoji=$(echo "$chosen_entry" | sed "s/ .*//")
echo "$chosen_emoji" | tr -d '\n' | "$CLIPBOARD"
notify-send "$chosen_emoji copied to clipboard" --category "Emoji!" --expire-time=1500
