#!/bin/sh

# Open files using floating fzf.
#

# – fzf (https://github.com/junegunn/fzf)
# – bat (https://github.com/sharkdp/bat)

if [ ! -d .git ]; then
    notify-send "kak-fzf-files: this is not a git directory" --expire-time=1000
    exit 1
fi

$FZF_DEFAULT_COMMAND \
| floating-fzf \
    --preview 'bat --style=numbers --color=always --line-range :500 {}' \
    --header='Select a file to open' \
    --prompt='(f)>' \
|

# Open files
while read file; do
  kcr edit "$file"
done
