#!/bin/sh

# prompt the user to select a screenshot type then do that screenshot

screenshot_options=(screen window selection)
screenshot_type=$(echo ${screenshot_options[*]} | tr "[:space:]" '\n' | fzf)
notify-send "Screenshot" "Screenshotting ${screenshot_type}" --expire-time=1500

case "$screenshot_type" in
    "screen")
        grim -c
        ;;
    "selection")
        grim -g "$(slurp)" -c
        ;;
    "window")
        # Use slurp to get the borders of a window
        window_borders=$(\
            swaymsg -t get_tree \
                | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' \
                | slurp
        )
        grim -g "${window_borders}" -c
        ;;
    *)
        exit 1
        ;;
esac

notify-send --expire-time=2500 "grim" "💻 Screenshot captured!"
