#!/bin/sh

update_weather() {
	# use silent mode so that we don't output connection information to the console
	curl -s "wttr.in/?format=1" > "$HOME/.local/share/weather_report"
}

show_weather() {
	cat "$HOME/.local/share/weather_report"
}

case $BLOCK_BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


# send error messages for the stat command to /dev/null
if [ "$(stat -c %y "$HOME/.local/share/weather_report" 2>&1 | awk '{print $1}')" != "$(date '+%F')" ]
then
	notify-send "Haven't checked weather in a day. Checking weather..."
	update_weather && show_weather
else
	show_weather
fi
